-- ADD A NEW NULLABLE COLUMN SAFELY
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;

-- RENAME A COLUMN
ALTER TABLE users RENAME COLUMN phone TO phone_number;

-- CHANGE A COLUMN TYPE SAFELY
ALTER TABLE orders ALTER COLUMN total_amount TYPE NUMERIC(12, 2) USING total_amount::NUMERIC(12, 2);
